services:
  db:
    image: postgres3
    env_file: .env
    expose:
      - '5432'
    volumes:
      - flickpick-db:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    working_dir: /repository
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
      - /repository/node_modules
    command: npm run testandrun
volumes:
  flickpick-db:
